name = "DiffEqUncertainty"
uuid = "ef61062a-5684-51dc-bb67-a0fcdec5c97d"
authors = ["Chris Rackauckas <accounts@chrisrackauckas.com>"]
version = "v1.2.0"

[deps]
DiffEqBase = "2b5f629d-d688-5b77-993f-72d75c75574e"

[compat]
julia = "1"
DiffEqBase = "6"

[extras]
DiffEqProblemLibrary = "a077e3f3-b75c-5d7f-a0c6-6bc4c8ec64a9"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["DiffEqProblemLibrary", "Test", "OrdinaryDiffEq"]
